TercumanSistemi/Controllers/CalisanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TercumanSistemi.Models.EntityFramework;

namespace TercumanSistemi.Controllers
{
    public class CalisanController : Controller
    {
        tercuman_dbEntities db = new tercuman_dbEntities();
        // GET: Calisan
        public ActionResult Index()
        {
            var siparisler = db.Tbl_Metin.ToList();
            return View(siparisler);
        }
        public ActionResult Goruntule(int id)
        {
            var siparis = db.Tbl_Metin.Find(id);
            return View(siparis);
        }
        [HttpGet]
        public ActionResult Cevir(int id)
        {
            var ceviri = db.Tbl_Metin.Find(id);
            return View(ceviri);
        }
        [HttpPost]
        public ActionResult Cevir(Tbl_Metin t)
        {
            var sprs = db.Tbl_Metin.Find(t.Id);
            sprs.Cev_metin = t.Cev_metin;
            sprs.Tam_onay = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CeviriGoruntule(int id)
        {
            var siparis = db.Tbl_Metin.Find(id);
            return View(siparis);
        }
    }
}

TercumanSistemi/Views/Calisan/Cevir.cshtml
@model TercumanSistemi.Models.EntityFramework.Tbl_Metin
@{
    ViewBag.Title = "Cevir";
    Layout = "~/Views/Shared/CalısanLayout.cshtml";
}

@using (Html.BeginForm("Cevir", "Calisan", FormMethod.Post))
{
    <label>Kaynak Dil:</label>
    @Html.TextBoxFor(x => x.kay_dil, new { @class = "form-control", @readonly = "readonly" })
    <br />
    <label>Hedef Dil:</label>
    @Html.TextBoxFor(x => x.hed_dil, new { @class = "form-control", @readonly = "readonly" })
    <br />

    <label>Çevirilecek Metin:</label>
    @Html.TextAreaFor(x => x.Metin, new { @class = "form-control", @readonly = "readonly" })

    <label>Çevrilmiş Metin:</label>
    @Html.TextAreaFor(x => x.Cev_metin, new { @class = "form-control" })
    @Html.HiddenFor(x => x.Id)
    <div style="margin-top: 10px">
        <button class="btn btn-info">Kaydet</button>
    </div>
}

TercumanSistemi/Views/Calisan/CeviriGoruntule.cshtml
﻿@model TercumanSistemi.Models.EntityFramework.Tbl_Metin
@{
    ViewBag.Title = "CeviriGoruntule";
    Layout = "~/Views/Shared/CalısanLayout.cshtml";
}

<label>Kaynak Dil:</label>
@Html.TextBoxFor(x => x.kay_dil, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Hedef Dil:</label>
@Html.TextBoxFor(x => x.hed_dil, new { @class = "form-control", @readonly = "readonly" })
<br />

<label>Çevirilecek Metin:</label>
@Html.TextAreaFor(x => x.Metin, new { @class = "form-control", @readonly = "readonly" })

<label>Çevrilmiş Metin:</label>
@Html.TextAreaFor(x => x.Cev_metin, new { @class = "form-control", @readonly = "readonly" })

TercumanSistemi/Views/Calisan/Goruntule.cshtml
﻿@model TercumanSistemi.Models.EntityFramework.Tbl_Metin
@{
    ViewBag.Title = "Goruntule";
    Layout = "~/Views/Shared/CalısanLayout.cshtml";
}

<label>Müşteri Adı:</label>
@Html.TextBoxFor(x => x.Tbl_Musteri.Ad, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Müşteri Soyadı:</label>
@Html.TextBoxFor(x => x.Tbl_Musteri.Soyad, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Çevirilecek Metin:</label>
@Html.TextAreaFor(x => x.Metin, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Sipariş Ücreti:</label>
@Html.TextBoxFor(x => x.Ucret, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Kaynak Dil:</label>
@Html.TextBoxFor(x => x.kay_dil, new { @class = "form-control", @readonly = "readonly" })
<br />
<label>Hedef Dil:</label>
@Html.TextBoxFor(x => x.hed_dil, new { @class = "form-control", @readonly = "readonly" })
<br />

TercumanSistemi/Views/Calisan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/CalısanLayout.cshtml";
}

@using TercumanSistemi.Models.EntityFramework
@model List<Tbl_Metin>

<h3>Gelen Siparişler</h3>
<div class="orders">
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Müşteri Adı</th>
            <th>Ücret</th>
            <th>Metni Görüntüle</th>
            <th>Metni Çevir</th>
        </tr>
        @foreach (var x in Model)
        {
            if (Session["KullaniciId"].ToString() == x.Calisan_id.ToString() && x.Onay == true && x.Tam_onay == false)
                {
            <tr>
                <td>@x.Id</td>
                <td>@x.Tbl_Musteri.Ad @x.Tbl_Musteri.Soyad</td>
                <td>@x.Ucret TL</td>
                <td><a href="~/Calisan/Goruntule/@x.Id" class="btn btn-info">Görüntüle</a></td>
                <td><a href="~/Calisan/Cevir/@x.Id" class="btn btn-success">Çevir</a></td>
            </tr>

                }
        }
    </table>
</div>
<h3>Geçmiş Siparişler</h3>
<div class="orders">
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Müşteri Adı</th>
            <th>Ücret</th>
            <th>Çeviri Metni Görüntüle</th>
        </tr>
        @foreach (var x in Model)
        {
            if (Session["KullaniciId"].ToString() == x.Calisan_id.ToString() && x.Tam_onay == true)
            {
            <tr>
                <td>@x.Id</td>
                <td>@x.Tbl_Musteri.Ad @x.Tbl_Musteri.Soyad</td>
                <td>@x.Ucret TL</td>
                <td><a href="~/Calisan/CeviriGoruntule/@x.Id" class="btn btn-info">Görüntüle</a></td>
            </tr>
            }
        }
    </table>
</div>