TercumanSistemi/Controllers/CalisanLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TercumanSistemi.Models.EntityFramework;
using System.Web.Security;

namespace TercumanSistemi.Controllers
{
    public class CalisanLoginController : Controller
    {
        tercuman_dbEntities db = new tercuman_dbEntities();
        // GET: CalisanLogin
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Tbl_Calisan t)
        {
            var bilgiler = db.Tbl_Calisan.FirstOrDefault(x => x.Eposta == t.Eposta && x.Sifre == t.Sifre);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.Eposta, false);
                Session["KullaniciId"] = bilgiler.Id;
                return RedirectToAction("Index", "Calisan");
            }
            else
            {
                return View();
            }
        }
    }
}

TercumanSistemi/Views/CalisanLogin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">

<head>
    <title>Giriş</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="~/login-form-20/css/style.css" rel="stylesheet" />
</head>

<body class="img js-fullheight" style="background-image: url(/login-form-20/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Çalışan Girişi</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        @using (Html.BeginForm("Index", "CalisanLogin", FormMethod.Post, new { @class = "signin-form" }))
                        {
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="E-Posta" name="Eposta" required>
                            </div>
                            <div class="form-group">
                                <input id="password-field" type="password" class="form-control" placeholder="Şifre" name="Sifre"
                                       required>
                                <span toggle="#password-field"
                                      class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary submit px-3">
                                    Giriş
                                    Yap
                                </button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Beni Hatırla
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="#" style="color: #fff">Şifremi Unuttum</a>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="/login-form-20/js/jquery.min.js"></script>
    <script src="/login-form-20/js/popper.js"></script>
    <script src="/login-form-20/js/bootstrap.min.js"></script>
    <script src="/login-form-20/js/main.js"></script>

</body>

</html>